In [13]:
import numpy as np
english_score = np.array([55,89,76,65,48,70])
math_score = np.array([60,85,60,68,np.nan,60])
chinese_score = np.array([65,90,82,72,66,77])

english_max=np.nanmax(english_score)
english_min=np.nanmin(english_score)
english_mean=np.nanmean(english_score)
english_std=np.nanstd(english_score)

print("英文:最大值:%d,最小值:%d,平均值:%d,標準差:%d" % (english_max , english_min , english_mean , english_std))

math_max=np.nanmax(math_score)
math_min=np.nanmin(math_score)
math_mean=np.nanmean(math_score)
math_std=np.nanstd(math_score)

print("數學:最大值:%d,最小值:%d,平均值:%d,標準差:%d"%(math_max,math_min,math_mean,math_std))

chinese_max=np.nanmax(chinese_score)
chinese_min=np.nanmin(chinese_score)
chinese_mean=np.nanmean(chinese_score)
chinese_std=np.nanstd(chinese_score)

print("國文:最大值:%d,最小值:%d,平均值:%d,標準差:%d"%(chinese_max,chinese_min,chinese_mean,chinese_std))



英文:最大值:89,最小值:48,平均值:67,標準差:13
數學:最大值:85,最小值:60,平均值:66,標準差:9
國文:最大值:90,最小值:65,平均值:75,標準差:8


In [14]:
#第五位同學補考數學後成績為55，請計算補考後數學成績平均、最大值、最小值、標準差?
math_score = np.array([60,85,60,68,55,60])
math_max=np.nanmax(math_score)
math_min=np.nanmin(math_score)
math_mean=np.nanmean(math_score)
math_std=np.nanstd(math_score)

print("英文:最大值:%d,最小值:%d,平均值:%d,標準差:%d" % (english_max , english_min , english_mean , english_std))
print("數學:最大值:%d,最小值:%d,平均值:%d,標準差:%d"%(math_max,math_min,math_mean,math_std))
print("國文:最大值:%d,最小值:%d,平均值:%d,標準差:%d"%(chinese_max,chinese_min,chinese_mean,chinese_std))

英文:最大值:89,最小值:48,平均值:67,標準差:13
數學:最大值:85,最小值:55,平均值:64,標準差:9
國文:最大值:90,最小值:65,平均值:75,標準差:8


In [19]:
#用補考後資料找出與國文成績相關係數最高的學科?

c1=np.corrcoef(math_score,chinese_score)
c2=np.corrcoef(math_score ,english_score)
c3=np.corrcoef(chinese_score,english_score)

print (c1,c2,c3)
# 國文與英文相關性最高

[[1.         0.74056803]
 [0.74056803 1.        ]] 
 [[1.        0.7855563]
 [0.7855563 1.       ]] 
 [[1.         0.97792828]
 [0.97792828 1.        ]]
